## In this assignment, by employing the lexical scoping principles in R, I 
## created to function for caching the calculation of the inverse of input
## matrices.

## The makeCacheMatrix function is used to store the cached calculations.It 
## gets a matrix and returns a special matrix object that will be 
## the input for cacheSolve function.

makeCacheMatrix <- function(matrix = matrix()) {
  
  inverse <- NULL
  
  set <- function(matrix_input) {
    matrix <<- matrix_input
    inverse <<- NULL  
  }
  
  get <- function() matrix
  
  getInverse <- function() inverse
  
  cacheInverse <- function(inverse_matrix) inverse <<- inverse_matrix
  
  list(set = set,
       get = get,
       getInverse = getInverse,
       cacheInverse = cacheInverse)
}


## The cacheSolve function gets the special matrix object generated by the
## makeCacheMatrix function. It first checks to see if there is a result 
## from previous calculations stored within the makeCacheMatrix 
## function's environment. If true, it returns the cached result, and if not it 
## calculates the inverse of the given matrix, stores the result within the 
## makeCacheMatrix, and then it prints it. :)

## It should be noted from mathematics we know that only square matrix with a 
## non-zero determinant (non-singular) are invertible. Consequently, in the 
## events that the input does not meet these conditions, using conditionals the 
## corresponding messages are returned with a NULL.

cacheSolve <- function(cacheMatrix, ...) {
  
  matrix <- cacheMatrix$get()
  cached_inverse <- cacheMatrix$getInverse()
  
  if(nrow(matrix) == ncol(matrix)) {
    
    if (!is.null(cached_inverse)) {
      message("Retrieving cached inverse...")
      return(cached_inverse)
    }
    
    else {
      
      if (det(matrix) == 0) {
        message("Matrix is singular and does not have an inverse.")
        return(NULL)
      }
      
      inverse <- solve(matrix, ...)
      
      cacheMatrix$cacheInverse(inverse)
      
      return(inverse)
    }
  }
    
  else{
     
     message("Matrix is not square and therefore, not invertible.")
     return(NULL)
     
   }

}

## In the end, I thank the instructor for their relentless efforts and valuable
## guidance.
